spring:
  application:
    name: notification
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbit}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

server:
  port: 8084

rabbitmq:
  queue:
    name: order.queue
  exchange:
    name: order.exchange
  routing:
    key: order.tracking