spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product
#    url: jdbc:mysql://localhost:3307/embarkx
    username: embarkx
    password: embarkx
  rabbitmq:
    connection-timeout: ${CONNECTION_TIMEOUT:30000}
    addresses: amqps://exnddjpl:t2JWuxv4dfjNPSCw-L9V9519lSM2DMSG@cougar.rmq.cloudamqp.com/exnddjpl
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

# File upload configuration
file:
  upload-dir: uploads

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    propagation:
      type: w3c,b3
    sampling:
      probability: 1.0

app:
  message: "Hello Product!"
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost

logging:
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 7