spring:
  data:
    mongodb:
      uri: mongodb+srv://sovannarithphan9_db_user:4TjhTw5-bQg824p@user-data.unip0bf.mongodb.net/?appName=user-data
      database: ecom_user
  rabbitmq:
    connection-timeout: ${CONNECTION_TIMEOUT:30000}
    addresses: amqps://exnddjpl:t2JWuxv4dfjNPSCw-L9V9519lSM2DMSG@cougar.rmq.cloudamqp.com/exnddjpl
server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    propagation:
      type: w3c,b3
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost


logging:
  file:
    name: logs/${spring.application.name}.log
  pattern:
    level: "%5p [service=${spring.application.name},trace_id=%X{traceId:-},span_id=%X{spanId:-}]"
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 7
