spring:
  application:
    name: configserver
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:////C:\Users\sovan\Desktop\Defend Project\fullstack\ecom-applications\configserver\src\main\resources\config
  rabbitmq:
    connection-timeout: ${CONNECTION_TIMEOUT:30000}
    addresses: amqps://exnddjpl:t2JWuxv4dfjNPSCw-L9V9519lSM2DMSG@cougar.rmq.cloudamqp.com/exnddjpl
#          search-locations: classpath:/config

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: "*"