spring:
  application:
    name: PAYMENT-SERVICE
  rabbitmq:
    listener:
      simple:
        observation-enabled: true
      direct:
        observation-enabled: true
    template:
      observation-enabled: true

server:
  port: 8089

payment:
  gateway:
    url: http://localhost:8976
  status:
    exchange: payment.status.exchange
    routing-key: payment.status.paid

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
  tracing:
    propagation:
      type: w3c,b3
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}

logging:
  level:
    com.ecom.payment: DEBUG
  file:
    name: logs/payment-service.log
  pattern:
    level: "%5p [service=${spring.application.name},trace_id=%X{traceId:-},span_id=%X{spanId:-}]"
