---
server:
  http_listen_address: 0.0.0.0
  http_listen_port: 3100

memberlist:
  join_members: ["read", "write", "backend"]
  dead_node_reclaim_time: 30s
  gossip_to_dead_nodes_time: 15s
  left_ingesters_timeout: 30s
  bind_addr: ['0.0.0.0']
  bind_port: 7946
  gossip_interval: 2s

schema_config:
  configs:
    - from: 2023-01-01
      store: tsdb
      object_store: s3
      schema: v13
      index:
        prefix: index_
        period: 24h

common:
  path_prefix: /loki
  replication_factor: 1
  compactor_address: http://backend:3100
  storage:
    s3:
      endpoint: minio:9000
      insecure: true
      bucketnames: loki-data
      access_key_id: loki
      secret_access_key: supersecret
      s3forcepathstyle: true
  ring:
    kvstore:
      store: memberlist

limits_config:
  retention_period: 24h
  # REQUIRED: This must exist for v13
  allow_structured_metadata: true
  max_query_length: 25h
  reject_old_samples: true
  reject_old_samples_max_age: 168h

compactor:
  working_directory: /tmp/compactor
  # Disable this switch as it is causing startup crashes with the v13 schema
  # The 1-day retention will still be handled by cleanups based on limits_config
  retention_enabled: false
  compaction_interval: 10m
  retention_delete_delay: 2h
  retention_delete_worker_count: 150

ruler:
  storage:
    s3:
      bucketnames: loki-ruler

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100
        ttl: 24h
  cache_results: true